server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://ec2-52-71-23-11.compute-1.amazonaws.com:5432/daki6bn5qr63kr
    username: vtctvlmushxaqg
    password: 6752f1fba3aca98e1b7f4788be88d6a51d96e1a09ce84c3388426d9912d75bf4
  jpa:
    hibernate:
      ddl-auto: update
#          ddl-auto: create
    show-sql: true
    open-in-view: true






