server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_management
    username: postgres
    password: 2211
  jpa:
    hibernate:
      ddl-auto: update
#          ddl-auto: create
    show-sql: true
    open-in-view: true






